parameters: { }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    # explicitly wire JwtService with env var
    App\Service\JwtService:
        arguments:
            $jwtSecret: '%env(resolve:JWT_SECRET)%'

